// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/categories" | "/categories/confused-words" | "/categories/confused-words/edit/[id]" | "/categories/confused-words/new" | "/categories/homonyms" | "/categories/homonyms/edit/[id]" | "/categories/homonyms/new" | "/categories/homophones" | "/categories/homophones/edit/[id]" | "/categories/homophones/new" | "/categories/word-categories" | "/categories/word-categories/[id]" | "/categories/word-categories/edit/[id]" | "/categories/word-categories/new" | "/dashboard" | "/idioms" | "/idioms/edit/[id]" | "/idioms/new" | "/phrasal-verbs" | "/phrasal-verbs/edit/[id]" | "/phrasal-verbs/new" | "/questions" | "/words" | "/words/[word]" | "/words/new"
type PageRoutes = never
type LayoutRoutes = "/" | "/categories"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/": {}
  "/categories": {}
  "/categories/confused-words": {}
  "/categories/confused-words/edit/[id]": { "id": string; }
  "/categories/confused-words/new": {}
  "/categories/homonyms": {}
  "/categories/homonyms/edit/[id]": { "id": string; }
  "/categories/homonyms/new": {}
  "/categories/homophones": {}
  "/categories/homophones/edit/[id]": { "id": string; }
  "/categories/homophones/new": {}
  "/categories/word-categories": {}
  "/categories/word-categories/[id]": { "id": string; }
  "/categories/word-categories/edit/[id]": { "id": string; }
  "/categories/word-categories/new": {}
  "/dashboard": {}
  "/idioms": {}
  "/idioms/edit/[id]": { "id": string; }
  "/idioms/new": {}
  "/phrasal-verbs": {}
  "/phrasal-verbs/edit/[id]": { "id": string; }
  "/phrasal-verbs/new": {}
  "/questions": {}
  "/words": {}
  "/words/[word]": { "word": string; }
  "/words/new": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/categories": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
