// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}


// Validate ../../app/categories/confused-words/edit/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categories/confused-words/edit/[id]">> = Specific
  const handler = {} as typeof import("../../app/categories/confused-words/edit/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/categories/confused-words/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categories/confused-words/new">> = Specific
  const handler = {} as typeof import("../../app/categories/confused-words/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/categories/confused-words/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categories/confused-words">> = Specific
  const handler = {} as typeof import("../../app/categories/confused-words/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/categories/homonyms/edit/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categories/homonyms/edit/[id]">> = Specific
  const handler = {} as typeof import("../../app/categories/homonyms/edit/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/categories/homonyms/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categories/homonyms/new">> = Specific
  const handler = {} as typeof import("../../app/categories/homonyms/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/categories/homonyms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categories/homonyms">> = Specific
  const handler = {} as typeof import("../../app/categories/homonyms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/categories/homophones/edit/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categories/homophones/edit/[id]">> = Specific
  const handler = {} as typeof import("../../app/categories/homophones/edit/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/categories/homophones/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categories/homophones/new">> = Specific
  const handler = {} as typeof import("../../app/categories/homophones/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/categories/homophones/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categories/homophones">> = Specific
  const handler = {} as typeof import("../../app/categories/homophones/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categories">> = Specific
  const handler = {} as typeof import("../../app/categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/categories/word-categories/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categories/word-categories/[id]">> = Specific
  const handler = {} as typeof import("../../app/categories/word-categories/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/categories/word-categories/edit/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categories/word-categories/edit/[id]">> = Specific
  const handler = {} as typeof import("../../app/categories/word-categories/edit/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/categories/word-categories/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categories/word-categories/new">> = Specific
  const handler = {} as typeof import("../../app/categories/word-categories/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/categories/word-categories/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/categories/word-categories">> = Specific
  const handler = {} as typeof import("../../app/categories/word-categories/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/idioms/edit/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/idioms/edit/[id]">> = Specific
  const handler = {} as typeof import("../../app/idioms/edit/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/idioms/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/idioms/new">> = Specific
  const handler = {} as typeof import("../../app/idioms/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/idioms/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/idioms">> = Specific
  const handler = {} as typeof import("../../app/idioms/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/phrasal-verbs/edit/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/phrasal-verbs/edit/[id]">> = Specific
  const handler = {} as typeof import("../../app/phrasal-verbs/edit/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/phrasal-verbs/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/phrasal-verbs/new">> = Specific
  const handler = {} as typeof import("../../app/phrasal-verbs/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/phrasal-verbs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/phrasal-verbs">> = Specific
  const handler = {} as typeof import("../../app/phrasal-verbs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/questions/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/questions">> = Specific
  const handler = {} as typeof import("../../app/questions/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/words/[word]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/words/[word]">> = Specific
  const handler = {} as typeof import("../../app/words/[word]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/words/new/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/words/new">> = Specific
  const handler = {} as typeof import("../../app/words/new/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/words/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/words">> = Specific
  const handler = {} as typeof import("../../app/words/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}







// Validate ../../app/categories/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/categories">> = Specific
  const handler = {} as typeof import("../../app/categories/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
